version: "3.8"

x-airflow-common: &airflow-common
  image: apache/airflow:2.9.1
  environment:
    &airflow-common-env
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://airflow:airflow@postgres/airflow
    AIRFLOW__CORE__FERNET_KEY: ""
    AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
    AIRFLOW__CORE__LOAD_EXAMPLES: "false"
    AIRFLOW__API__AUTH_BACKENDS: "airflow.api.auth.backend.basic_auth"
  volumes:
    - ./dags:/opt/airflow/dags
    - ./logs:/opt/airflow/logs
    - ./plugins:/opt/airflow/plugins
    - ./requirements.txt:/requirements.txt
  depends_on:
    postgres:
      condition: service_healthy
  extra_hosts:
    - "host.docker.internal:host-gateway"

services:
  metrics_postgres:
    image: postgres:15
    ports:
      - "5435:5432"
    networks:
      - elt_network
    env_file:
      - .env.postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
  extract_load_open_signal:
    build:
      context: ./elt/open_signal
      dockerfile: Dockerfile
    command: ["python", "extract_load.py"]
    volumes:
      - ./data:/data
    env_file:
      - .env.pg
    networks:
      - elt_network
    depends_on:
      metrics_postgres:
        condition: service_healthy
  dbt:
    image: ghcr.io/dbt-labs/dbt-postgres:1.4.7
    command: ["run", "--profiles-dir", "/root", "--project-dir", "/dbt"]
    networks:
      - elt_network
    volumes:
      - ./custom_postgres:/dbt
      - ~/.dbt:/root
    depends_on:
      extract_load_open_signal:
        condition: service_completed_successfully 
    env_file:
      - .env.dbt
  postgres:
    image: postgres:15
    env_file:
      - .env.airflow
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "airflow"]
      interval: 5s
      retries: 5

  airflow-init:
    <<: *airflow-common
    command: >
      bash -c "
        airflow db init &&
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com
      "
    environment:
      <<: *airflow-common-env

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8080/health"]
      interval: 10s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    restart: unless-stopped
    env_file:
      - .env.airflow
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  elt_network:
    driver: bridge

volumes:
  postgres-db-volume:
