version: 2

sources:
  - name: raw_high_utilization
    schema: public
    description: "Raw high utilization data loaded from open signal xlsx file"
    tables:
      - name: raw_high_utilization
        description: "Raw high utilization data"
        columns:
          - name: week
            tests: [not_null]
          - name: date
            tests: [not_null]
          - name: tech
            tests: [not_null]
          - name: vendor
            tests: [not_null]
          - name: site_no
            tests: [not_null]
          - name: site_name
            tests: [not_null]
          - name: cell_name
            tests: [not_null]
          - name: municipality
            tests: [not_null]
          - name: province
            tests: [not_null]
          - name: area
            tests: [not_null]
          - name: band
            tests: [not_null]